localStorage.setItem(
  "access_token",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJzczIwNTNAc3JtaXN0LmVkdS5pbiIsImV4cCI6MTc3NzcwMTUwMSwiaWF0IjoxNzc3NzAwNjAxLCJpc3MiOiJBZmZvcmQgTWVkaWNhbCBUZWNobm9sb2dpZXMgUHJpdmF0ZSBMaW1pdGVkIiwianRpIjoiMjI4NTk4NmYtN2E4OS00ZWYxLTkyNjQtMWFkYzg0M2YyNDA3IiwibG9jYWxlIjoiZW4tSU4iLCJuYW1lIjoic3VkaGlyIGt1bWFyIHNpbmdoIiwic3ViIjoiMTVlNTRkOTAtZjIwNy00ODI5LWFhNmQtMzgzNWQyNzJiZjFhIn0sImVtYWlsIjoic3MyMDUzQHNybWlzdC5lZHUuaW4iLCJuYW1lIjoic3VkaGlyIGt1bWFyIHNpbmdoIiwicm9sbE5vIjoicmEyMzExMDAzMDExNDUzIiwiYWNjZXNzQ29kZSI6IlFrYnB4SCIsImNsaWVudElEIjoiMTVlNTRkOTAtZjIwNy00ODI5LWFhNmQtMzgzNWQyNzJiZjFhIiwiY2xpZW50U2VjcmV0Ijoia3pOR0pDVmhGUFJqU3hqayJ9.h7SjY1lbBbXeP_JQhKRGD-14xj5mBTwg_bMEelxhpfU"
);

import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
